site_name: diego-utils My Playbook for Data Science

# mkdocs.yml
theme:
  name: "material"
  logo: assets/diego_logo.svg
  favicon: assets/diego_favicon.svg

plugins:
  - search
  - mkdocstrings

repo_name: diego-utils
repo_url: https://github.com/diego-lda/diego-utils.git

nav:
  - Introduction: index.md
  - High Level Overview: high_level.md
  - Git and Sustainability: git_sustainability.md
  - Python Style Guide: python_overview.md
  - Data Science Projects: project_guide.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/diego-lda/diego-utils.git

# Do not remove the copy right section. But you can change the copyright information.
copyright: |
  &copy;  <a href="https://diego-lda.github.io/">Diego Lara 2024</a>