site_name: Diego's Python Utilities and Guidance for Data Science

# mkdocs.yml
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

repo_name: diego-utils
repo_url: https://github.com/diego-lda/diego-utils.git

nav:
  - diego-utils: index.md
  - High Level Overview: high_level.md
  - Useful Git: git_overview.md
  - Useful Python: python_overview.md
  - Branching & Deployment Guide: branch_and_deploy_guide.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/diego-lda/diego-utils.git

# Do not remove the copy right section. But you can change the copyright information.
copyright: |
  &copy;  <a href="https://diego-lda.github.io/">Diego Lara 2024</a>