site_name: Diego's Python Utilities and Guidance for Data Science

theme:
  name: readthedocs

repo_name: diego-utils
repo_url: https://github.com/diego-lda/diego-utils.git

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            # All options can be found at: https://mkdocstrings.github.io/python/usage/#globallocal-options
            docstring_style: numpy
            show_signature_annotations: True
            show_source: False
            show_root_heading: True
            merge_init_into_class: True
  - material/search
  - git-revision-date-localized
  - mkdocs-jupyter:
      include_source: True
      include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
      ignore: ["*.py"]
      remove_tag_config:
        remove_input_tags:
          - hide_code
        remove_all_outputs_tags:
          - hide_out
  - mermaid2

nav:
  - High Level Overview: high_level.md
  - Useful Git: git_overview.md
  - Useful Python: python_overview.md
  - Branching & Deployment Guide: branch_and_deploy_guide.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/diego-lda/diego-utils.git

# Do not remove the copy right section. But you can change the copyright information.
copyright: |
  &copy;  <a href="https://diego-lda.github.io/">Diego Lara 2024</a>