site_name: diego-utils My Playbook for Data Science

# mkdocs.yml
theme:
  name: "material"
  logo: assets/diego_logo.svg
  favicon: assets/diego_favicon.svg
  palette:
    - scheme: default        # Light Mode Colours
      primary: "#fa2738"
      accent: "#ef2ebb"
      background: "#ffffff"
      surface: "#f0f0f0"    
      text: "#333333"        
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - scheme: slate          # Dark Mode Colours
      primary: "#ef2ebb"
      accent: "#fa2738"
      background: "#121212"  
      surface: "#2d2d2d"    
      text: "#f5f5f5"
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode    
  features:
    - navigation.tabs
    - navigation.top
    - toggle.light_dark  # Enables light/dark mode toggle

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: materialx.emoji.twemoji
      emoji_generator: materialx.emoji.to_svg

repo_name: diego-utils
repo_url: https://github.com/diego-lda/diego-utils.git

nav:
  - Introduction: index.md
  - High Level Overview: high_level.md
  - Git and Sustainability: git_sustainability.md
  - Python Style Guide: python_overview.md
  - Data Science Projects: project_guide.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/diego-lda/diego-utils.git

# Do not remove the copy right section. But you can change the copyright information.
copyright: |
  &copy;  <a href="https://diego-lda.github.io/">Diego Lara 2024</a>